dist: focal
arch: ppc64le
service: docker
before_script:
  - |
    if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]
    then
      # fix cpu count in ppc64le to avoid OOM failure
      cat /proc/stat > /tmp/stat
      sed -i '/^cpu[2-9]/d' /tmp/stat
      sed -i '/^cpu[0-9][0-9]/d' /tmp/stat
      sudo mount --bind /tmp/stat /proc/stat
      sudo systemctl restart docker
    fi

script:
  - cat /sys/fs/cgroup/cpuset/docker/cpuset.cpus
  - free -h
  - df -h
  - cat /proc/stat
  - nproc
  - docker run -t centos:7 bash -c 'cat /proc/stat && nproc'
